# Format: language id = "translated message"

[manifest_name]
# Full name of the extension.
en = "Ghostbird - GhostText for Thunderbird"
ja = "Ghostbird - Thunderbird用GhostText"

[manifest_description]
# Description of the extension.
en = "Use your favorite text editor to compose emails"
ja = "お好みのテキストエディタでメールを編集"

[manifest_commands_start_ghostbird_description]
# Description of the shortcut key to start Ghostbird.
en = "Start syncing with the text editor"
ja = "テキストエディタとの同期を開始"

[manifest_commands_stop_ghostbird_description]
# Description of the shortcut key to stop Ghostbird.
en = "End syncing with the text editor (Set the same keys as Start to toggle)"
ja = "テキストエディタとの同期を停止 (開始と同じキーにすることでトグルになります)"
